const textData = {
  0: "",
  1: "<strong>Fecha de publicación:</strong> Marzo de 2024 </br>  <strong>Lugar:</strong> Estado Plurinacional de Bolivia</br> </br> <b>Institución responsable:</b> </br> Viceministerio de Educación Superior de Formación Profesional</br>Dirección General de Formación de Maestros</br>Unidad Especializada de Formación Continua – UNEFCO</br> </br> <b>Equipo de redacción y dirección:</b> </br>Fundación Ayuda en Acción </br> ProggettoMondo </br> Unidad Especializada de Formación Continua – UNEFCO </br> </br> <b>Créditos de las imágenes y flujogramas:</b> </br>Ilustraciones y dibujos: Fundación Ayuda en Acción; ProgettoMondo </br> Flujogramas: Fundación Ayuda en Acción </br>   </br> <b>Sitios oficiales:</b> </br> www.minedu.gob.bo </br> http://unefco.gob.bo/ </br> Bolivia, marzo, 2024 ",
  2: "texto a remplazarC",
  3: "<br> <br> <br>  El Plan de Formación para Maestras y Maestros es una modalidad de aprendizaje, compuesta por cursos cortos, desarrollada por el Ministerio de Educación a través de la Unidad Especializada de Formación Continua (UNEFCO) para profundizar y fortalecer habilidades y capacidades en la labor educativa, con un enfoque en la mejora de las prácticas y procesos formativos. Su propósito, de acuerdo con la Ley de Educación N° 070 “Avelino Siñani – Elizardo Pérez”, es trabajar por la universalización del Modelo Educativo Sociocomunitario Productivo, en atención a los diferentes niveles y áreas temáticas, con relevancia cultural y lingüística. <br> <br> Las prácticas restaurativas se han venido consolidando como una ciencia social emergente desde aproximadamente el 2013, época en la cual se estudian las acciones individuales y efectivas dirigidas hacia tres objetivos: el fortalecimiento comunitario, la resolución pacífica de conflictos y la  del daño o falta u ofensa cuando se produce. Se definen las mismas como respuestas no punitivas orientadas a la reparación del daño, potenciar las relaciones interpersonales, fortalecer la resolución de los conflictos y desarrollar soluciones que incluyan a todas las personas involucradas en un daño o falta u ofensa; tomando en cuenta que el manejo restaurativo de los afectos en el aula mejora la capacidad para el aprendizaje y la resiliencia. <br> <br> Los cuadernos del ciclo formativo: <b> “PRÁCTICAS RESTAURATIVAS PARA LA RESOLUCIÓN DE CONFLICTOS Y UNA VIDA LIBRE DE VIOLENCIA” </b>, nos invitan a replantearnos la manera en que enfrentamos los conflictos, desafiando los paradigmas arraigados de confrontación y castigo. A medida que nos sumergimos en las profundidades de las prácticas restaurativas, descubrimos su capacidad no solo para restaurar el daño o falta u ofensa causado por los conflictos, sino también para fortalecer nuestros lazos comunitarios y fomentar un clima de confianza y respeto mutuo. Este ciclo cuenta con tres cursos, en el Primer Curso, se aborda la parte normativa, lo que es y no es conflicto para luego introducir al enfoque restaurativo; en el Segundo Curso, se presenta; y en el Tercer Curso presentamos una caja de herramientas práctica para la aplicación en el quehacer educativo. <br> <br><b> COORDINACIÓN GENERAL - UNEFCO",
  4: " <br>  <br> <b>OBJETIVO HOLÍSTICO DEL CICLO</b> <br> Fortalecemos en maestras y maestros la responsabilidad de ser los principales actores en la resolución de conflictos, desarrollando su análisis y reflexión sobre los principios del enfoque restaurativo, promoviendo la incorporación de las prácticas restaurativas en sus procesos de interacción cotidianos, tomando decisiones para la promoción de una convivencia, pacífica, armónica y libre de violencia en su comunidad educativa. <br><br> <b> OBJETIVO HOLÍSTICO DEL CURSO</b><br> Identificamos condiciones para prácticas educativas restaurativas, su implementación en la resolución de conflictos y a la prevención de la violencia, con participación activa de integrantes de la comunidad educativa, para contar con espacios educativos restaurativos. <br>",
  5: " ",
  6: "Esta actividad busca activar tus saberes iniciales y generar un espacio de diálogo sobre cómo comprendemos la justicia, la convivencia y la reparación del daño dentro de la comunidad educativa. <br><br>   A partir de preguntas detonadoras, experiencias compartidas o mapas conceptuales, podrás identificar cómo se relacionan los valores restaurativos con tu práctica cotidiana, y sentar las bases para un aprendizaje significativo y contextualizado. <br><br>  Recuerda <b> descargar la plantilla </b> Actividad de inicio tema 1 o abrirla en la carpeta de <b> recursos adicionales </b> para llenar tus respuestas.",
  7: "",
  8: " Para profundizar en <b>  Aspectos fundamentales de la justicia restaurativa en la unidad educativa </b>, avanza con las flechas para revisar más información.",
  9: " ",

  10: "",
  11: "Para profundizar sobre <b>  la Violencia Escolar</b>, avanza con las flechas para revisar más información. ",
  12: "",
  13: "Para profundizar sobre <b> Tipos de violencia escolar </b>, avanza con las flechas para revisar más información. ",
  14: [
    "<br>  <br> El bullying, acoso escolar o maltrato entre pares se presenta <b>tanto en niñas, niños de primaria como en adolescentes y jóvenes, mujeres y hombres</b>. De hecho, suele atribuirse a adolescentes, mujeres u hombres, que manifiestan ciertas características consideradas propias de <b>maltratadores típicos, tales como una tiranía premeditada, continua, malévola y despreciable; graves problemas de conducta desde edades tempranas, agresividad, robo de cosas, mentiras constantes y consumo de sustancias psicoactivas</b>. (Maritza Garcia y Cristian Amaury, 2019)",
    "Las formas que adquiere el acoso escolar o bullying son <b>verbales (insultos, majaderías, burlas, bromas pesadas)</b>; <b>físicas (empujones, patadas, pellizcos, golpes, romper la ropa)</b>; <b>sexuales (tocamientos irrespetuosos)</b>; <b>sociales, de indiferencia y ostracismo (el hacer a un lado a la persona, sobre todo del grupo)</b>; <b>virtuales, mediante el cyberbullying o intimidación por la red, ya sea a través de teléfonos móviles o de redes sociales, como Facebook, Twitter, o por correos electrónicos o páginas virtuales</b>. (Maritza Garcia y Cristian Amaury, 2019)",
  ],
  15: [
    "<br><br>En la actualidad, el bullying o acoso escolar se relaciona con las nuevas tecnologías que ponen al alcance niveles mayores de daño o falta u ofensa, humillación y anonimato al impedir el contacto de las capas emocionales que inhiben la agresión; esto da lugar a prácticas de maltrato que rebasan las fronteras espaciotemporales.",
    "La violencia entre pares <b>casi siempre tiene lugar lejos de la presencia de personas adultas, maestras/maestros, madre/padre, otros del mundo adulto</b>. Dado que <b>las consecuencias pueden llegar a ser irreversibles para la integridad personal, el equilibrio psicológico y el rendimiento académico de la víctima</b>, es necesaria <b>su identificación oportuna para intervenir lo antes posible con las medidas educativas y de protección previstas para estos casos</b>.",
  ],
  16: " ",
  17: "Para profundizar sobre <b>  las consecuencias emocionales por agresión</b>, avanza con las flechas para revisar más información.  ",
  18: [
    "<br> La <b>Justicia Restaurativa</b> es una filosofía y una propuesta educativa integral que se basa en el <b>respeto mutuo</b> y la <b>resolución pacífica de conflictos</b> en la comunidad educativa. Las <b>prácticas restaurativas</b>, como herramientas sencillas pero efectivas, contribuyen a establecer <b>relaciones sanas, crear <b>espacios de diálogo</b>, fomentar el <b>liderazgo positivo</b> y el <b>empoderamiento</b>, promover <b>comportamientos responsables</b> y reducir los <b>comportamientos violentos</b>, <b>reparar el daño</b> y <b>restaurar las relaciones</b>.<br>  La <b>Justicia Restaurati-va</b> se enfoca en las <b>víctimas</b> y busca <b>reparar el daño</b> cometido a través del conflicto o la comisión de delito, mientras que la <b>práctica restaurativa</b> se puede aplicar de forma <b>proactiva</b>, <b>preventiva</b> y <b>reactiva</b>, y no necesita que exista delito para aplicarse.",
    "Las <b>prácticas restaurativas</b> en el ámbito educativo abor-dan los conflictos desde un enfoque <b>social</b>, <b>afectivo</b>, <b>pedagógico</b> y de <b>derechos</b>, orientado por los principios de <b>protección integral</b> e <b>interés superior</b> de niñas, niños y adolescentes (mujeres y hombres). Diferentes investigaciones prueban que el modelo de <b>gestión de conflictos</b> basado en el enfoque restaurativo <b>frena la reincidencia</b>, facilita la <b>restauración de relaciones</b> entre las perso-nas implicadas, ayuda a instaurar un <b>sentimiento de pertenencia</b> a la comunidad, favorece la <b>reparación de los daños</b> en el grupo de estudiantes víctimas o en el caso que haya sido una víctima de manera individual y aumenta la <b>implicación personal</b> en la resolución del conflicto y la <b>reparación del daño</b>.",
  ],
  19: " ",
  20: "Para profundizar sobre <b> Prácticas restaurativas no formales </b>, avanza con las flechas para revisar más información.",
  21: "Esta actividad tiene como objetivo promover una comprensión más profunda sobre los principios, objetivos y beneficios de la <b> justicia restaurativa </b> en el entorno educativo. A través del análisis, el diálogo y la reflexión conjunta, podrás identificar cómo esta perspectiva va más allá de una forma de resolver conflictos, y se convierte en una herramienta para fortalecer los vínculos, construir comunidad y reparar el daño de manera participativa. <br> <br>  <b> La participación activa y el trabajo colaborativo serán clave </b> para nutrir esta experiencia de aprendizaje y avanzar hacia comunidades escolares más justas, empáticas y restaurativas. <br> <br> Recuerda <b> descargar la plantilla </b> Actividad sugerida tema 1 o abrirla en la carpeta de <b> recursos adicionales </b> para llenar tus respuestas.",
  22: " ",
  23: "Para comenzar el segundo tema de este curso, te invitamos a reflexionar sobre los elementos que componen una <b>  comunidad educativa restaurativa. </b>  Esta actividad busca identificar, a partir de tus experiencias, ideas clave relacionadas con la convivencia, la participación, el cuidado mutuo y la reparación del daño. <br> <br> <b> Este ejercicio te ayudará a conectar lo vivido con los principios restaurativos</b>, y será la base para seguir profundizando en herramientas concretas que promuevan entornos escolares más seguros, empáticos y solidarios. <br> <br>  Recuerda <b> descargar la plantilla </b> Actividad de inicio tema 2 o abrirla en la carpeta de <b> recursos adicionales </b> para llenar tus respuestas. ",
  24: "",
  25: "Para profundizar sobre <b> las bases de una comunidad educativa restaurativa </b>, avanza con las flechas para revisar más información. ",
  26: "<br><b>Maestras y maestros</b> pueden ser <b>facilitadores</b> de <b>prácticas restaurativas</b> en el ámbito educativo. “Estas prácticas buscan <b>mejorar la convivencia escolar</b> al crear <b>vínculos</b> entre los miembros de la comunidad, resolviendo <b>conflictos</b> a partir del <b>diálogo</b> y creando <b>entornos positivos</b> con la <b>participación</b> de toda la comunidad educativa”. (educacionyfp.gob.es, 2020). <br> <br> La figura de la persona que actúa <b>facilitando</b> en las prácticas restaurativas es recomendable que sea <b>asumida</b> y <b>comprendida</b> por <b>maestras y maestros</b>, <b>personal directivo</b> y <b>personal administrativo</b> en su plenitud, para que así puedan <b>realizar</b> y <b>organizar</b>, tanto las prácticas como la <b>metodología de intervención</b> en la comunidad educativa.",
  27: " ",
  28: "<br> <b>Promover las prácticas restaurativas</b> en la comunidad educativa por parte de <b>maestras y maestros</b> es importante, siendo que estos se convierten en el <b>agente de cambio</b>, previniendo la <b>vulneración de derechos</b> de estudiantes, como también <b>futuros problemas de conducta</b>, evitando el surgimiento de la <b>violencia</b>, y evitando que estudiantes se acerquen a la <b>comisión de delito</b>.<br> <br> No debemos olvidar que dependerá de <b>maestras y maestros</b> <b>establecer las conexiones</b> en el aula, creando <b>oportunidades</b> para que estudiantes, niñas, niños y adolescentes, mujeres y hombres, puedan <b>establecer conexiones</b>, estén en relación con el <b>aprendizaje académico</b> y, también, con estudiantes de su curso y <b>nivel estudiantil</b>.",
  29: [
    "<br> La resolución de conflictos en el entorno escolar es una oportunidad para fomentar el diálogo, la empatía y la corresponsabilidad. Ante una situación de conflicto, <b> la maestra o el maestro desempeñan un rol clave como mediadores</b>, facilitando procesos de comu-nicación imparciales y respetuosos que permitan restablecer la convivencia. Su intervención activa y neutral contribuye a generar un ambiente más relajado, seguro y propicio para el aprendizaje. <br>",
    "<br> <br> Se debe evitar ser observador pasivo de conflictos que en los que pudieren estar estudiantes de la comunidad educativa, más al contrario, debe intervenir inmediatamente ante conflictos y situaciones de violencia leves, con el fin de detener el ciclo de la violencia y proponer modos de resolución de conflictos por la vía pacífica",
  ],
  30: "<br> <b>Maestras y maestros</b> y el <b>personal administrativo</b> de la unidad educativa pueden ayudar en la <b>resolución de conflictos</b> y la <b>prevención de violencias</b>; sin embargo, no debemos olvidar que <b>madres/padres</b> y <b>tutores</b> de familia son <b>actores importantes</b> para que también se pueda implementar las prácticas  <b>restaurativas</b>. <br> <br> De acuerdo con el <b>Reglamento de Participación Social Comunitario en Educación</b>, <b>padres y madres de familia</b>, <b>Juntas Escolares</b>, y los <b>Concejos Educativos</b> deben apoyar acciones de <b>prevención</b> y <b>control</b> contra todo tipo de <b>violencia</b> dentro de la <b>Unidad Educativa</b>, en coordinación con las <b>autoridades educativas</b>.",
  31: "Para profundizar sobre <b>  estudiantes como protagonistas de las prácticas restaurativas </b>, avanza con las flechas para revisar más información. ",
  32: [
    "<br>Los procesos de prácticas restaurativas en comunidades educativas coadyuvan a la prevención de violencias entre los diferentes actores de la comunidad. Siendo uno de ellos: niñas, niños, adolescentes, es decir, estudiantes, mujeres y hombres, quienes al promover y ser parte de los procesos restaurativos pueden emitir sus opiniones, sus sentimientos ante una situación de conflicto en la que está involucrado directa e indirectamente.",
    "En ese sentido se hace necesario que estudiantes reciban una formación en la implementación de las prácticas restaurativas, siendo que al conocer los instrumentos o mecanismos de la misma, se fortalecerá también diferentes habilidades sociales personales, la cohesión grupal, la importancia de ser parte de una comunidad educativa y reconocer que toda conducta influye a todo el sistema educativo.",
  ],
  33: [
    "<br> <br> El grupo de estudiantes, mujeres u hombres, al ser participantes activos del proceso, naturalmente tienen una percepción positiva de la metodología y recomiendan la implementación de prácticas restaurativas. Aun así, cobra relevancia que la perspectiva de ellos se orienta a que estos sean más escuchados por las personas adultas y que ellos, como estamento estudiantil estén mejor capacitados para resolver conflictos, además que el trabajo entre pares es más factible de realizarlo.",
    "Involucrar a estudiantes en la resolución de conflictos de y con sus pares, en algunas situaciones se hace más productivo siendo que el proceso puede ser implementado desde un punto de vista, más de sus vivencias, considerando que tienen las mismas edades.",
  ],
  34: "<br> La <b>participación</b> de <b>madre, padre o tutor</b> de familia en <b>procesos restaurativos</b> es importante, porque las familias provienen de <b>distintos entornos</b>, con <b>formas de analizar la realidad</b> y determinadas <b>maneras de ver la realidad</b> y una <b>cultura</b> que son transmitidos a <b>hijas e hijos</b>. <br> <br> Cabe mencionar que la <b>infancia</b>, como la <b>adolescencia</b>, son etapas donde hay <b>diferentes cambios</b> en niñas, niños y mujeres y hombres adolescentes, los cuales a veces generan <b>conflictos</b> con las familias y la <b>unidad educativa</b>. <br><br>  Es por ello por lo que se hace necesario que <b>madre/padre o tutor</b> de familia puedan ser <b>partícipes continuamente</b> de estos procesos, que <b>beneficiará</b> a sus hijos e hijas, no olvidando que forman parte de una <b>comunidad educativa</b>.",
  35: "En esta actividad te proponemos reflexionar y actuar en torno al papel que cada actor educativo —docentes, estudiantes, madres y padres de familia, equipo directivo— desempeña en la construcción de una <b> comunidad educativa restaurativa. </b> A partir del análisis de casos, intercambio de experiencias o elaboración de propuestas, podrás identificar acciones concretas que promuevan la participación, el respeto mutuo y la corresponsabilidad. <br> <br> El objetivo es generar ideas y compromisos para que el enfoque restaurativo no sea solo una teoría, sino una práctica viva en la vida escolar cotidiana. <br> <br> Recuerda <b> descargar la plantilla </b> Actividad sugerida tema 2 o abrirla en la carpeta de <b> recursos adicionales </b> para llenar tus respuestas.",
  36: "",
  37: "En toda comunidad educativa, la forma en que cada actor se involucra en los procesos de convivencia y resolución de conflictos tiene un impacto significativo. Esta actividad te invita a reflexionar sobre el rol actual de la maestra o maestro, estudiantes, madres/padres de familia y el Consejo Educativo, reconociendo cómo han participado ante situaciones de conflicto. . <br> <br> A partir de esta mirada, se te propondrá imaginar cómo cambiaría esa historia si cada uno asumiera un rol activo desde el enfoque restaurativo, basado en el diálogo, la corresponsabilidad y la reparación del daño. <br> <br> Recuerda <b> descargar la plantilla </b> Actividad de inicio tema 3 o abrirla en la carpeta de <b> recursos adicionales </b> para llenar tus respuestas.",
  38: [
    "<br> <br> </br>Podemos identificar dos finalidades en el desarrollo de las prácticas restaurativas, la primera de ellas está en la <b> prevención de maltrato, daño u ofensa que puede darse entre pares y no pares</b>, mediante un abordaje asertivo de las situaciones de violencias en la unidad educativa; y, la segunda está en relación con la <b> búsqueda de la responsabilidad, a veces, de la corresponsabilidad y la reparación del daño por parte de la víctima </b>, de la persona que actúa como ofensor y de la comunidad, en general, cuando se ha producido acciones que están en relación con la violencia.",
    "Es decir que por estos mismos motivos se estable una doble condición: por un lado, como estrategias para la prevención, referidas a la posibilidad de emitir acciones que impidan o eviten esas acciones de maltrato o violencia en la unidad educativa; por otra parte, también son herramientas que permiten que se pueda atender y buscar el restablecimiento de las relaciones sociales que se deterioran a causa de una acción ya cometida",
  ],
  39: " ",
  40: "En una zona restaurativa, cada integrante de la comunidad educativa cumple un rol fundamental en la construcción de un entorno basado en el respeto, la reparación del daño y la convivencia pacífica. Los niños, niñas, adolescentes y adultos ofensores son beneficiarios directos del proceso restaurativo, en el que se busca generar conciencia sobre la responsabilidad de sus acciones y su impacto en los demás, promoviendo su reintegración y cambio de conducta. <br> Las bases de una comunidad educativa (Hopkins, 2020) está conformada por los actores que intervienen en las prácticas restaurativas en las unidades educativas son:",
  41: "<b> Planificación docente </b> <br><br> Es importante que la maestra o el maestro elabore un plan de práctica restaurativa para una convivencia pacífica y armónica, cuya finalidad es abordar las problemáticas sociales y/o conflictos en las unidades educativas de manera restaurativa y no así punitiva.<br> <br>  <b>  Directrices para un reglamento interno con enfoque restaurativo </b> <br><br>  Las directrices de contenido de un reglamento interno con enfoque restaurativo deben contemplar los siguientes puntos, sin olvidar la Ley 548 Código de la Niña, Niño y Adolescente.",
  42: "Para profundizar sobre <b>  planes de convivencia pacífica</b>, avanza con las flechas para revisar más información. ",
  43: "Invitamos a revisar el Ciclo Formativo “Planes de Convivencia Pacífica y Armónica, donde encontrarás mayor detalle de este apartado ",
  44: "Las personas que han ido aplicando las <b>prácticas restaurativas</b> en su ámbito laboral, como <b>personal</b>, son de los que se puede recuperar <b>experiencias</b> y <b>vivencias enriquecedoras</b>, siendo uno de ellos la experiencia de <b>Jena Schmitz</b>, quien refiere lo siguiente: <br>  <br> “Las <b>comunidades educativas</b> con <b>cultura restaurativa</b> han desarrollado <b>relaciones sanas y seguras</b> entre todos sus actores, han promovido <b>comportamientos saludables y responsables</b>, han logrado reducir <b>comportamientos ofensivos y violentos</b>, han prevenido y gestionado <b>tensiones y conflictos</b>, han generado estudiantes <b>empáticos</b>, <b>responsables</b>, <b>empoderados</b> y con <b>liderazgo</b>, y aunque parezca sorprendente, han mejorado también el <b>rendimiento académico</b> del estudiantado.”  <br> <br> “Un <b>centro educativo restaurativo</b> es un espacio que considera las <b>relaciones interpersonales</b> como elementos claves e indispensables para la <b>convivencia sana y pacífica</b>. Por ello, su principal objetivo es crear un <b>sentido de comunidad</b> entre todos sus actores, desarrollando, fortaleciendo y manteniendo <b>relaciones sanas, seguras y fuertes</b>, buscando prevenir <b>situaciones tensas, problemáticas y conflictivas</b>, abordándolas oportunamente cuando ocurran, implicando a todos los involucrados para <b>comprender la situación</b> y encontrar juntos la <b>mejor solución</b> a lo sucedido, <b>reparando los daños</b> o faltas u ofensas causados y evitando que vuelva a suceder en el futuro. Todo <b>conflicto</b> es una profunda fuente de <b>aprendizaje</b>.” (Manuel Ortega, VVOB Ecuador, 2022)",
  45: "",
  46: "Para profundizar sobre <b>  señalética con mensajes restaurativos en la unidad educativa</b>, avanza con las flechas para revisar más información. ",
  47: "Las <b>zonas restaurativas</b> en las comunidades educativas son <b>espacios diseñados</b> para fomentar la <b>convivencia sana y segura</b>, utilizando la <b>filosofía restaurativa</b> como base. Esta se fundamenta en la convicción de que se puede mejorar la <b>convivencia humana</b> cuando las personas se sienten que forman parte de una <b>comunidad</b> y se sienten <b>escuchadas</b> y <b>respetadas</b>.<br> La implementación de <b>zonas restaurativas</b> en las comunidades educativas puede contribuir a la creación de un <b>ambiente escolar positivo</b>, en el que se protegen las <b>relaciones personales sanas</b> y se educa a los estudiantes en valores como el <b>respeto</b>, la <b>tolerancia</b> y el <b>compromiso</b>. Además, las <b>zonas restaurativas</b> pueden ser una <b>herramienta efectiva</b> para la <b>resolución de conflictos</b> y la <b>gestión de las relaciones</b> entre los miembros de la comunidad educativa. (<b>Albertí & Pedrol, 2017</b>)",
  48: "En este punto del curso, te invitamos a dar un paso hacia la <b>  acción colectiva </b>, reflexionando sobre cómo sería posible construir una <b>  zona restaurativa </b> en tu unidad educativa. Esta actividad busca que, junto a tus compañeras y compañeros, identifiques los recursos, actitudes y compromisos necesarios para implementar un espacio donde el diálogo, la reparación y la participación activa sean parte del día a día escolar. <br> <br> A través de esta propuesta, podrás analizar las condiciones actuales de tu entorno educativo, proyectar mejoras y pensar en <b>  estrategias reales y sostenibles </b>  que fortalezcan la convivencia pacífica. <br> <br> Recuerda <b> descargar la plantilla </b> Actividad sugerida tema 3 o abrirla en la carpeta de <b> recursos adicionales </b> para llenar tus respuestas.",
  49: [
    "¡Te animamos a poner en práctica lo aprendido! Tomando en cuenta los contenidos desarrollados en el presente cuaderno de formación, llevamos adelante un diagnóstico que permita identificar los tipos de violencias, faltas que afectan a las y los estudiantes dentro de la comunidad educativa.",
    "Analizamos qué información requerimos para identificar los tipos de faltas e infracciones (violencias) más frecuentes que enfrentan nuestras y nuestros estudiantes. <br>  Analizamos qué información requerimos para identificar las formas y/o resolución de conflictos en la comunidad educativa. <br> Recopilamos la información disponible con que cuenta la dirección sobre los casos conocidos durante la gestión sobre violencia entre pares. Al mismo tiempo de las formas que se ha ido utilizando para abordar este tipo de casos. <br> Realizamos entrevistas a los estudiantes para saber cuáles son los problemas y/o conflictos más recurrentes en este sentido. También es útil la información de las personas adultas de la comunidad educativa, es decir del plantel docente administrativo y el concejo educativo de padres, madres de familia.",
    "<b>Según la información que hemos recolectado:</b><br> ¿Cuáles son los tipos de violencia, problemas y/o conflictos presentes entre las y los estudiantes? <br> ¿Qué género y edad realiza más faltas y/ o son parte de un conflicto? <br> ¿En qué medida resulta útil esta información?<br> ¿En qué medida las estadísticas ignoran a maestros y maestras?, ¿por qué? <br> ",
    " <b> Conclusiones</b> <br> Sistematizamos la información y la plasmamos en gráficos y tablas sencillas.<br> Luego, sacamos las conclusiones que se desprenden de esta y, finalmente, trabajamos con un pequeño grupo de estudiantes para generar una zona restaurativa, aplicando prácticas restaurativas, con un enfoque preventivo, para analizar con ellos las alternativas para cambiar los hallazgos del diagnóstico. ",
    " <b>Estrategias para la etapa de socialización de experiencias<b><br> <br> Compartimos en plenaria el proceso del diagnóstico y la metodología del recojo de la información, además de los logros y dificultades, y las conclusiones. <br> Compartimos también el proceso que tuvimos con los/as estudiantes en los círculos restaurativos y cómo pensamos que eso podría aportar a la convivencia. Finalmente, con apoyo de la facilitación, analizamos los aspectos relevantes que servirán para nuestra práctica diaria.",
  ],
  50: "<b>Comisión de delito</b>: El delito se caracteriza por ser una conducta descrita en el Código Penal, que es realizada por una persona natural, y puede, o no, tener la intención de hacer daño. Así́ mismo, debe ser comprobable mediante un juicio y existir un daño efectivo al bien jurídico de otro. <br> <br>   <b>Comunidad</b>: Es un concepto multidimensional que puede acoger tanto un espacio geográfico o territorio definido, como el conjunto de relaciones que entretejen las personas; así́, emerge el sentimiento de pertenecer a un grupo e intereses comunes. Es una relación construida sobre el afecto, los fines y los valores comunes, así́ como en la lealtad y la reciprocidad entre sus miembros. <br> <br>   <b>Comunidad Educativa</b>: Engloba a todos los miembros de la institución educativa, incluyendo estudiantes, directoras/es, maestras y maestros, personal administrativo, madres y padres de familias, que ayudan en la promoción de un ambiente de convivencia positiva. <br> <br>   <b>Corresponsabilidad</b>: Hace referencia al deber que tiene la familia, el Estado y la sociedad en relación con la atención cuidado y protección de estudiantes: niñas, niños y adolescentes, mujeres y hombres. <br> <br>   <b>Delito y/o falta</b>: Se refiere a aquellas acciones que, además más allá de afectar a una persona en particular, tienen repercusiones en el entorno educativo en su conjunto. <br> <br>   <b>Delito</b>: Es un comportamiento de manera voluntaria o por imprudencia atenta contra los derechos de otras personas, es una acción u omisión que puede convertirse en una infracción de la ley penal, de las normas establecidas. Atenta contra las personas, cuando se trata de vulnerar derechos como el respeto y la dignidad, por ejemplo, cuando se presenta violencia física o sexual y el respeto a la propiedad privada. <br> <br>",
  51: "<b>Disciplina</b>: En el ámbito educativo, la disciplina se refiere al conjunto de normas que regulan la convivencia en las unidades educativas. Estas normas no solo se refieren al mantenimiento del orden colectivo, sino también a la creación de hábitos de organización y respeto entre cada actor participante de la comunidad educativa, haciendo énfasis en los estudiantes, mujeres y hombres, por el proceso de aprendizaje. <br> <br> <b>Enfoque centrado en soluciones</b>: Busca resolver los problemas de la manera más rápida, eficiente y menos dolorosa, busca atacar el problema en el presente, en el “aquí y ahora”. <br> <br> <b>Enfoque de disciplina positiva</b>: Este enfoque educativo y parental que se centra en enseñar habilidades y comportamientos positivos, en lugar de castigar o reprimir los comportamientos negativos. Se basa en el respeto mutuo, la comunicación abierta y la enseñanza de habilidades sociales y emocionales. <br> <br> <b>Enfoque de factor de riesgos de la violencia</b>: Referente a la situación que incrementa las posibilidades de ser afectado por problemas que van a influir negativamente en el desarrollo normal de un individuo, un grupo o una comunidad. <br> <br> <b>Enfoque de protección de la violencia</b>: Es una habilidad o recurso que favorece el desarrollo humano, el mantenimiento o la recuperación de la salud y que permite a las personas, familias, escuelas o sociedad enfrentar con mayor eficacia situaciones de riesgo y; por lo tanto, reducir la vulnerabilidad. <br> <br>",
  52: "<b>Enfoque Psico-educacional</b>: Se centra en la labor que el profesional encargado de la gestión de los conflictos dentro de la unidad educativa, aplicando estrategias que promueven la gestión de las relaciones en el ámbito educativo, evitando centrarse únicamente en la conducta del estudiante y buscando preservar las relaciones entre estudiantes y maestras, maestros, dando la oportunidad de generar ambientes más positivos y donde los actores se hagan responsables de los roles que les corresponde. <br> <br>   <b>Enfoque restaurativo</b>: Entiende la dimensión humana de cada caso y brinda a las personas implicadas el espacio para transformar el conflicto y salir fortalecidas en valores y con habilidades para enfrentar nuevos retos. <br> <br>   <b>Enfoque sistémico</b>: Se considera a la familia y la escuela como sistemas que se relacionan entre sí de forma interdependiente. <br> <br>   <b>Facilitador de Prácticas Restaurativas</b>: Persona encargada de guiar y moderar los procesos restaurativos, asegurando un ambiente seguro y propicio para la resolución de conflictos. <br> <br>   <b>Justicia Restaurativa</b>: Tipo de justicia que surge de prácticas ancestrales, en la que se considera al delito como un daño a las relaciones sociales. En la medida de lo posible, involucra a la víctima, ofensor y comunidad para atender colectivamente los daños, necesidades y obligaciones derivados de la acción, con el propósito de sanar y generar reparación a las partes involucradas. <br> <br>   <b>La violencia escolar</b>: Incluye agresiones físicas (golpes, puñetazos, patadas), agresiones verbales (amenazas, burlas, apodos, rumores, entre otros), exclusión social, y además pueden presentarse agresiones sexuales (tocamientos no consentidos, relaciones sexuales forzadas). <br> <br>",
  53: "<b>Ofensor/a</b>: Persona que genera un daño individual o colectivo. <br> <br>  <b>Prácticas ancestrales</b>: Actividades propias de los pueblos o comunidades indígenas, que nacen de su cosmovisión y permiten comprender o dar respuesta a su realidad. <br> <br>   <b>Prácticas Restaurativas</b>: Son métodos y técnicas que aplican los principios de la justicia restaurativa en entornos educativos, con el objetivo de mejorar la convivencia y resolver conflictos. <br> <br>   <b>Reparación del Daño</b>: Implica identificar y abordar las consecuencias negativas de un conflicto, buscando restablecer la armonía y la confianza entre las personas afectadas. <br> <br>   <b>Señalética</b>: Técnica comunicacional que, mediante señales y símbolos icónicos, lingüísticos y cromáticos, orienta y brinda instrucción sobre cómo debe accionar una persona o un grupo de personas en un determinado espacio o ambiente físico. <br> <br>   <b>Víctima</b>: Persona que sufre un daño (físico, psicológico, material, etc.) ofensa (de palabra o acciones) por causas externas a su voluntad. <br> <br>   <b>Zona Restaurativa</b>: Es un espacio para una mayor coexistencia pacífica donde las autoridades, los ciudadanos y las instituciones públicas y privadas adoptan el enfoque de prácticas restaurativas como política social y lo aplican en todas sus acciones y relaciones de la vida cotidiana. <br> <br>",
  54: "<b>Albertí, M., & Pedrol, M. (2017)</b>. www.raco.cat. Obtenido de ´https://www.raco.cat <br> <br>  <b>Albertí i Cortés, M., & Pedrol Llirinós, M. (s.f.)</b>. El enfoque restaurativo en el ámbito educativo. Cuando innovar la escuela es humanizarla. Educació Social. Revista d’Intervenció Socioeducativa, 67, 47-72. <br> <br>   <b>Bisquerra, R., & Perez, N. (2007)</b>. Las competencias emocionales. Barcelona, España: Educación XXI. <br> <br>   <b>Bisquerra, R. (2011)</b>. Educación emocional: Propuestas para educadores y familia. Bilbao, España: Desclée de Brouwer, S.A. <br> <br>   <b>Canedo, A. (2014)</b>. Pasado, presente y futuro del periodismo. La Paz, Bolivia: Plural Editores. <br> <br>   <b>Diariodemediacion.es. (2018)</b>. Obtenido de https://www.diariodemediacion.es/diferencias-entre-justicia-restaurativa-y-practica-restaurativa/ <br> <br>   <b>Educación.gob.ec. (2018)</b>. Prácticas restaurativas en el ámbito educativo. Obtenido de https://educacion.gob.ec/practicas-restaurativas-en-el-ambito-educativo/ <br> <br>   <b>Educacionyfp.gob.es. (2020)</b>. Obtenido de https://www.educacionyfp.gob.es/mc/sgctie/convivencia-escolar/en-accion/practicas-restaurativas.html <br> <br>   <b>Eposgrado.com. (2019)</b>. Obtenido de https://www.epostgrado.com/practicas-restaurativas-otra-opcion-para-la-resolucion-de-conflictos-pacificas/´<br>  ",
  55: " <b>Estado Plurinacional de Bolivia; Ministerio de Educación. (2018)</b>. Protocolo de Prevención, Actuación y Denuncia en casos de violencia física, psicológica y sexual en Unidades Educativas y centros de Educación Especial. La Paz, Bolivia. <br> <br> <b>Fundacionesplai.org. (2023)</b>. Obtenido de ´https://fundacionesplai.org/blog/justicia-educativa/el-enfoque-de-la-justicia-restaurativa/´ <br> <br>  <b>García Montañez, M. V., & Ascensio Martínez, C. A. (2015)</b>. Bullying y violencia escolar: diferencias, similitudes, actores, consecuencias y origen. Revista Intercontinental de Psicología y Educación, 9-38. <br> <br>  <b>Gonzales, C. I. (2022)</b>. Obtenido de https://uvadoc.uva.es/bitstream/handle/10324/57806/TFG-O-2187.pdf <br> <br>  <b>Hopkins, B. (2020)</b>. Prácticas restaurativas en el aula. Palma, España: GOIB. <br> <br>  <b>Informe de 2013. (2016)</b>. Promover la justicia restaurativa para las niñas, niños y adolescentes. New York, Estados Unidos: Oficina del representante Especial del Secretario General sobre la violencia contra los niños. <br> <br>  <b>López, R. N. (2023)</b>. Fundación Esplai Restaurativa. Obtenido de https://fundacionesplai.org/blog/justicia-educativa/el-enfoque-de-la-justicia-restaurativa/ <br> <br>  <b>Maritza Garcia y Cristian Amaury. (2019)</b>. Universidad Intercontinental. Obtenido de https://www.uic.mx/bullying-violencia-escolar-diferencias-similitudes-actores-consecuencias-origen/ <br> <br>  <b>Matos Gamboa, J. (2012)</b>. Obtenido de www.eumed.net: https://www.eumed.net/rev/17/jmg.hmtl <br> ",
  56: "<b>Paulero, R. (2021)</b>. Conflictos entre docentes y directivos de nivel primario. Representaciones, vivencias, comportamientos y consecuencias en la práctica docente. Revista Latinoamericana de Políticas y Administración de la Educación, 140-152. <br> <br>  <b>Progettomondo.Mlal, EDUCO, FUDEP. (2018)</b>. Prácticas Restaurativas para la prevención y gestión de conflictos en el ámbito educativo. La Paz, Bolivia: Imprenta Cerro Azul S.R.L. <br> <br> <b>Revista Pedagógos. (2013, mayo)</b>. El papel del alumno de ser activo. Obtenido de ´https://revista-pedagogos6.webnode.com.co/paulo-freire/su-pensamiento/´ <br> <br>   <b>Rodríguez, R. (2005)</b>. La acción tutorial para favorecer la convivencia: la disciplina. <br> <br>   <b>San Martín, J. A. (2003)</b>. La mediación escolar. Un camino para la gestión del conflicto escolar. Madrid, España. <br> <br>  <b>Schmitz, J. (2020)</b>. Prácticas restaurativas en el ámbito educativo. Ecuador. <br> <br>  <b>Terres des hommes. (2014)</b>. Auditoría Social de niños, niñas y adolescentes ¿Es tiempo de derechos? Cochabamba, Bolivia: Kipus. <br> <br>  <b>Trusco, D., & Inostroza, P. (2017, marzo)</b>. Las violencias en el espacio escolar. Naciones Unidas. <br> <br>  <b>UNEFCO. (2022)</b>. Ciclo: Promoviendo la convivencia pacífica y armónica en Unidades Educativas. Tarija, Bolivia: UNEFCO. <br> <br>  ",
  57: " <b>UNICEF. Santander, F. (2019)</b>. Estrategia Nacional de Prevención de la Violencia contra Niñas, Niños, Adolescentes y Mujeres. La Paz, Bolivia: Viceministerio de Seguridad Ciudadana. <br> <br> <b>Vargas, G. (2019)</b>. Factores protectores y afrontamiento de riesgos asociados al uso de sustancias psicoactivas en adolescentes y jóvenes. La Paz, Bolivia: WA-GUI. <br> <br>  <b>Zehr, H. (2007, julio)</b>. Obtenido de https://www.icbf.gov.co/sites/default/files/el_pequeno_libro_de_las_justicia_restaurativa.pdf <br> <br>  <b>Zimmermann, A. (2000)</b>. Gestión de cambio organizacional. Caminos y herramientas. Ecuador: Ediciones Abya-Yala. <br> <br>",
};
const titlesData = {
  0: "",
  1: "De la justicia restaurativa a las prácticas educativas",
  2: "CONTENIDO",
  3: "Presentación",
  4: "DATOS GENERALES DEL CUADERNO",
  5: "",
  6: "¿Qué entendemos por justicia restaurativa?",
  7: "Justicia restaurativa",
  8: "Aspectos fundamentales de la justicia restaurativa en la unidad educativa",
  9: "Principios básicos de la Justicia Restaurativa",
  10: "Concepto del daño o falta u ofensa, falta u ofensa individual o colectiva.",
  11: "La violencia escolar",
  12: "Manifestación de la violencia escolar",
  13: "Tipos de la violencia en el sistema educativo",
  14: [
    "<br> El bullying, acoso escolar",
    "Formas que adquiere el acoso escolar o bullying ",
  ],
  15: [
    "<br> El bullying o acoso escolar en la actualidad",
    "Características del bullying o acoso escolar ",
  ],
  16: "Necesidades que se generan a partir por delito o falta",
  17: "Consecuencias emocionales por agresión",
  18: [
    "El aporte de la justicia restaurativa a la práctica restaurativa escolar",
    "Justicia Restaurativa y su Impacto en la Comunidad Educativa",
  ],
  19: "Práctica Restaurativa en la Educación",
  20: "Prácticas restaurativas no formales",
  21: "Aplicación de principios del enfoque restaurativo ",
  22: "",
  23: "Comunidad restaurativa",
  24: "Hacia una Comunidad Restaurativa:",
  25: "Las bases de una comunidad educativa restaurativa",
  26: "Maestras y maestros como facilitadores de las prácticas restaurativas",
  27: "Las prácticas restaurativas ofrecen un marco teórico y práctico",
  28: "Para la prevención",
  29: "Para la resolución de conflictos",
  30: "Consejo educativo en la prevención de conflictos",
  31: "Estudiantes como protagonistas de las prácticas restaurativas",
  32: [
    "<br>Estrategia de Prevención",
    "El Rol del Estudiante en la Prevención de la Violencia",
  ],
  33: [
    "<br> Resolución de Conflictos",
    "Desarrollo de Habilidades para una Convivencia Pacífica",
  ],
  34: "Participación restaurativa de madre, padre o tutor de familia",
  35: "Análisis de caso",
  36: "",
  37: "Historia de una situación de conflicto",
  38: [
    "<br>Finalidades en el desarrollo de las prácticas restaurativas",
    "Prácticas restaurativas novedosas",
  ],
  39: "Concepto y características de una zona restaurativa",
  40: "Definimos el rol de los integrantes de la comunidad educativa en una zona restaurativa.",
  41: "Actividades con enfoque restaurativo",
  42: "Planes de convivencia pacífica",
  43: " ",
  44: "Vivencia de las prácticas restaurativas",
  45: "Prácticas restaurativas en las comunidades educativas ",
  46: "Señalética con mensajes restaurativos en la unidad educativa",
  47: "Beneficios de una zona educativa restaurativa",
  48: "Análisis de caso",
  49: "Consignas de aplicación",
  50: "Glosario",
  51: "Glosario",
  52: "Glosario",
  53: "Glosario",
  54: "Bibliografía",
  55: "Bibliografía",
  56: "Bibliografía",
  57: "Bibliografía",
};

const layoutData = {
  0: "Alayout",
  1: "Blayout",
  2: "Clayout",
  3: "Blayout",
  4: "Dlayout",
  5: "Elayout",
  6: "Flayout",
  7: "Olayout",
  8: "Jlayout",
  9: "Olayout",
  10: "Playout",
  11: "Jlayout",
  12: "Playout",
  13: "Jlayout",
  14: "Glayout",
  15: "Glayout",
  16: "Olayout",
  17: "Jlayout",
  18: "Glayout",
  19: "Olayout",
  20: "Jlayout",
  21: "Flayout",
  22: "Elayout",
  23: "Flayout",
  24: "Olayout",
  25: "Jlayout",
  26: "Dlayout",
  27: "Jlayout",
  28: "Dlayout",
  29: "Klayout",
  30: "Dlayout",
  31: "Jlayout",
  32: "Glayout",
  33: "Glayout",
  34: "Dlayout",
  35: "Flayout",
  36: "Elayout",
  37: "Flayout",
  38: "Glayout",
  39: "Jlayout",
  40: "Llayout",
  41: "Dlayout",
  42: "Jlayout",
  43: "Ilayout",
  44: "Olayout",
  45: "Olayout",
  46: "Jlayout",
  47: "Dlayout",
  48: "Flayout",
  49: "Mlayout",
  50: "Blayout",
  51: "Blayout",
  52: "Blayout",
  53: "Blayout",
  54: "Blayout",
  55: "Blayout",
  56: "Blayout",
  57: "Blayout",
};

const popUpData = {
  0: " ",
  1: "",
  2: "",
  3: "",
  4: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG4POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG4POP-2.png",
      buttonName: "Abrir",
    },
  ],
  5: "",
  6: "",
  7: "",
  8: "",
  9: "",
  10: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG10POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG10POP-2.png",
      buttonName: "Abrir",
    },
  ],
  11: "",
  12: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG12POP-1.png",
      buttonName: "Abrir",
    },
  ],
  13: "",
  14: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG14POP-1.png",
      buttonName: "Manifestación del bullying",
    },
  ],
  15: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG15POP-1.png",
      buttonName: "Internet y Bullying",
    },
  ],
  16: "",
  17: "",
  18: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG18POP-1.png",
      buttonName: "Fortalecer sentido de comunidad",
    },
  ],
  19: "",
  20: "",
  21: "",
  22: "",
  23: "",
  24: "",
  25: "",
  26: [
    {
      title: " ",
      typeofContent: "text",
      contentModal:
        "Las prácticas restaurativas en el ámbito educativo se basan en el desarrollo de la comunidad a partir del fortalecimiento de los vínculos. Cuando se dan conflictos en la vida del centro, lo que se busca es la reparación de los daño o falta u ofensas causados asumiendo responsabilidades. (Gonzales, 2022)",
      buttonName: "Abrir",
    },
  ],
  27: "",
  28: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG28POP-1.png",
      buttonName: "Abrir",
    },
  ],
  29: "",
  30: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-1.png",
      buttonName: "Abrir",
    },
  ],
  31: "",
  32: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG32POP-1.png",
      buttonName: "Estudiante consciente",
    },
  ],
  33: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG33POP-1.png",
      buttonName: "Prevención de conflictos estudiantiles",
    },
  ],
  34: [
    {
      title: "Para la prevención de conflictos y violencia",
      typeofContent: "image",
      contentModal: "PAG34POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG34POP-2.png",
      buttonName: "Abrir",
    },
  ],
  35: "",
  36: "",
  37: "",
  38: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG38POP-1.png",
      buttonName: "Zona restaurativa",
    },
  ],
  39: "",
  40: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-1.png",

      buttonName: "El niño, niña, adolescente o persona adulta ofensora",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-2.png",

      buttonName: "El niño, niña, adolescente o persona adulta víctima",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-3.png",

      buttonName: "La comunidad educativa",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-4.png",
      buttonName: "Facilitadores de la práctica",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-5.png",
      buttonName: "Las autoridades de gestión y dirección",
    },
  ],
  41: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG41POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG41POP-2.png",
      buttonName: "Abrir",
    },
  ],
  42: "",
  43: "",
  44: "",
  45: "",
  46: "",
  47: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG47POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG47POP-2.png",
      buttonName: "Abrir",
    },
  ],
  48: "",
  49: "",
  50: "",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
  58: "",
};
const popUp_xs_Data = {
  0: " ",
  1: "",
  2: "",
  3: "",
  4: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG4POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG4POP-2.png",
      buttonName: "Abrir",
    },
  ],
  5: "",
  6: "",
  7: "",
  8: "",
  9: "",
  10: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG10POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG10POP-2.png",
      buttonName: "Abrir",
    },
  ],
  11: "",
  12: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG12POP-1.png",
      buttonName: "Abrir",
    },
  ],
  13: "",
  14: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG14POP-1.png",
      buttonName: "Manifestación del bullying",
    },
  ],
  15: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG15POP-1.png",
      buttonName: "Internet y Bullying",
    },
  ],
  16: "",
  17: "",
  18: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG18POP-1.png",
      buttonName: "Fortalecer sentido de comunidad",
    },
  ],
  19: "",
  20: "",
  21: "",
  22: "",
  23: "",
  24: "",
  25: "",
  26: [
    {
      title: " ",
      typeofContent: "text",
      contentModal:
        "Las prácticas restaurativas en el ámbito educativo se basan en el desarrollo de la comunidad a partir del fortalecimiento de los vínculos. Cuando se dan conflictos en la vida del centro, lo que se busca es la reparación de los daño o falta u ofensas causados asumiendo responsabilidades. (Gonzales, 2022)",
      buttonName: "Abrir",
    },
  ],
  27: "",
  28: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG28POP-1.png",
      buttonName: "Abrir",
    },
  ],
  29: "",
  30: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-1.png",
      buttonName: "Abrir",
    },
  ],
  31: "",
  32: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG32POP-1.png",
      buttonName: "Estudiante consciente",
    },
  ],
  33: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG33POP-1.png",
      buttonName: "Prevención de conflictos estudiantiles",
    },
  ],
  34: [
    {
      title: "Para la prevención de conflictos y violencia",
      typeofContent: "image",
      contentModal: "PAG34POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG34POP-2.png",
      buttonName: "Abrir",
    },
  ],
  35: "",
  36: "",
  37: "",
  38: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG38POP-1.png",
      buttonName: "Zona restaurativa",
    },
  ],
  39: "",
  40: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-1.png",

      buttonName: "El niño, niña, adolescente o persona adulta ofensora",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-2.png",

      buttonName: "El niño, niña, adolescente o persona adulta víctima",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-3.png",

      buttonName: "La comunidad educativa",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-4.png",
      buttonName: "Facilitadores de la práctica",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-5.png",
      buttonName: "Las autoridades de gestión y dirección",
    },
  ],
  41: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG41POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG41POP-2.png",
      buttonName: "Abrir",
    },
  ],
  42: "",
  43: "",
  44: "",
  45: "",
  46: "",
  47: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG47POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG47POP-2.png",
      buttonName: "Abrir",
    },
  ],
  48: "",
  49: "",
  50: "",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
  58: "",
};
const popUp_sm_Data = {
  0: " ",
  1: "",
  2: "",
  3: "",
  4: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG4POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG4POP-2.png",
      buttonName: "Abrir",
    },
  ],
  5: "",
  6: "",
  7: "",
  8: "",
  9: "",
  10: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG10POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG10POP-2.png",
      buttonName: "Abrir",
    },
  ],
  11: "",
  12: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG12POP-1.png",
      buttonName: "Abrir",
    },
  ],
  13: "",
  14: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG14POP-1.png",
      buttonName: "Manifestación del bullying",
    },
  ],
  15: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG15POP-1.png",
      buttonName: "Internet y Bullying",
    },
  ],
  16: "",
  17: "",
  18: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG18POP-1.png",
      buttonName: "Fortalecer sentido de comunidad",
    },
  ],
  19: "",
  20: "",
  21: "",
  22: "",
  23: "",
  24: "",
  25: "",
  26: [
    {
      title: " ",
      typeofContent: "text",
      contentModal:
        "Las prácticas restaurativas en el ámbito educativo se basan en el desarrollo de la comunidad a partir del fortalecimiento de los vínculos. Cuando se dan conflictos en la vida del centro, lo que se busca es la reparación de los daño o falta u ofensas causados asumiendo responsabilidades. (Gonzales, 2022)",
      buttonName: "Abrir",
    },
  ],
  27: "",
  28: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG28POP-1.png",
      buttonName: "Abrir",
    },
  ],
  29: "",
  30: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-1.png",
      buttonName: "Abrir",
    },
  ],
  31: "",
  32: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG32POP-1.png",
      buttonName: "Estudiante consciente",
    },
  ],
  33: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG33POP-1.png",
      buttonName: "Prevención de conflictos estudiantiles",
    },
  ],
  34: [
    {
      title: "Para la prevención de conflictos y violencia",
      typeofContent: "image",
      contentModal: "PAG34POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG34POP-2.png",
      buttonName: "Abrir",
    },
  ],
  35: "",
  36: "",
  37: "",
  38: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG38POP-1.png",
      buttonName: "Zona restaurativa",
    },
  ],
  39: "",
  40: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-1.png",

      buttonName: "El niño, niña, adolescente o persona adulta ofensora",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-2.png",

      buttonName: "El niño, niña, adolescente o persona adulta víctima",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-3.png",

      buttonName: "La comunidad educativa",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-4.png",
      buttonName: "Facilitadores de la práctica",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-5.png",
      buttonName: "Las autoridades de gestión y dirección",
    },
  ],
  41: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG41POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG41POP-2.png",
      buttonName: "Abrir",
    },
  ],
  42: "",
  43: "",
  44: "",
  45: "",
  46: "",
  47: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG47POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG47POP-2.png",
      buttonName: "Abrir",
    },
  ],
  48: "",
  49: "",
  50: "",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
  58: "",
};
const popUp_md_Data = {
  0: " ",
  1: "",
  2: "",
  3: "",
  4: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG4POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG4POP-2.png",
      buttonName: "Abrir",
    },
  ],
  5: "",
  6: "",
  7: "",
  8: "",
  9: "",
  10: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG10POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG10POP-2.png",
      buttonName: "Abrir",
    },
  ],
  11: "",
  12: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG12POP-1.png",
      buttonName: "Abrir",
    },
  ],
  13: "",
  14: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG14POP-1.png",
      buttonName: "Manifestación del bullying",
    },
  ],
  15: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG15POP-1.png",
      buttonName: "Internet y Bullying",
    },
  ],
  16: "",
  17: "",
  18: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG18POP-1.png",
      buttonName: "Fortalecer sentido de comunidad",
    },
  ],
  19: "",
  20: "",
  21: "",
  22: "",
  23: "",
  24: "",
  25: "",
  26: [
    {
      title: " ",
      typeofContent: "text",
      contentModal:
        "Las prácticas restaurativas en el ámbito educativo se basan en el desarrollo de la comunidad a partir del fortalecimiento de los vínculos. Cuando se dan conflictos en la vida del centro, lo que se busca es la reparación de los daño o falta u ofensas causados asumiendo responsabilidades. (Gonzales, 2022)",
      buttonName: "Abrir",
    },
  ],
  27: "",
  28: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG28POP-1.png",
      buttonName: "Abrir",
    },
  ],
  29: "",
  30: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-1.png",
      buttonName: "Abrir",
    },
  ],
  31: "",
  32: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG32POP-1.png",
      buttonName: "Estudiante consciente",
    },
  ],
  33: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG33POP-1.png",
      buttonName: "Prevención de conflictos estudiantiles",
    },
  ],
  34: [
    {
      title: "Para la prevención de conflictos y violencia",
      typeofContent: "image",
      contentModal: "PAG34POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG34POP-2.png",
      buttonName: "Abrir",
    },
  ],
  35: "",
  36: "",
  37: "",
  38: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG38POP-1.png",
      buttonName: "Zona restaurativa",
    },
  ],
  39: "",
  40: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-1.png",

      buttonName: "El niño, niña, adolescente o persona adulta ofensora",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-2.png",

      buttonName: "El niño, niña, adolescente o persona adulta víctima",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-3.png",

      buttonName: "La comunidad educativa",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-4.png",
      buttonName: "Facilitadores de la práctica",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-5.png",
      buttonName: "Las autoridades de gestión y dirección",
    },
  ],
  41: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG41POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG41POP-2.png",
      buttonName: "Abrir",
    },
  ],
  42: "",
  43: "",
  44: "",
  45: "",
  46: "",
  47: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG47POP-1.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG47POP-2.png",
      buttonName: "Abrir",
    },
  ],
  48: "",
  49: "",
  50: "",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
  58: "",
};
const images_xs_Data = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: "PAG4-1.png",
  5: "PAG5-1.png",
  6: ["PAG6-1.png", "PAG6-2.png"],
  7: "PAG7-1.png",
  8: ["PAG8-1.png", "PAG8-2.png", "PAG8-3.png", "PAG8-4.png", "PAG8-5.png"],
  9: "PAG9-1.png",
  10: "PAG10-1.png",
  11: [
    "PAG11-1.png",
    "PAG11-2.png",
    "PAG11-3.png",
    "PAG11-4.png",
    "PAG11-5.png",
  ],
  12: "PAG12-1.png",
  13: [
    "PAG13-1.png",
    "PAG13-2.png",
    "PAG13-3.png",
    "PAG13-4.png",
    "PAG13-5.png",
  ],
  14: "",
  15: "",
  16: "PAG16-1.png",
  17: [
    "PAG17-1.png",
    "PAG17-2.png",
    "PAG17-3.png",
    "PAG17-4.png",
    "PAG17-5.png",
  ],
  18: "",
  19: "PAG19-1.png",
  20: [
    "PAG20-1.png",
    "PAG20-2.png",
    "PAG20-3.png",
    "PAG20-4.png",
    "PAG20-5.png",
  ],
  21: ["PAG21-1.png", "PAG21-2.png"],
  22: "PAG22-1.png",
  23: ["PAG23-1.png", "PAG23-2.png"],
  24: "PAG24-1.png",
  25: [
    "PAG25-1.png",
    "PAG25-2.png",
    "PAG25-3.png",
    "PAG25-4.png",
    "PAG25-5.png",
  ],
  26: "PAG26-1.png",
  27: [
    "PAG27-1.png",
    "PAG27-2.png",
    "PAG27-3.png",
    "PAG27-4.png",
    "PAG27-5.png",
  ],
  28: "PAG28-1.png",
  29: "PAG29-1.png",
  30: "PAG30-1.png",
  31: [
    "PAG31-1.png",
    "PAG31-2.png",
    "PAG31-3.png",
    "PAG31-4.png",
    "PAG31-5.png",
  ],
  32: "",
  33: "",
  34: "PAG34-1.png",
  35: ["PAG35-1.png", "PAG35-2.png"],
  36: "PAG36-1.png",
  37: ["PAG37-1.png", "PAG37-2.png"],
  38: "",
  39: [
    "PAG39-1.png",
    "PAG39-2.png",
    "PAG39-3.png",
    "PAG39-4.png",
    "PAG39-5.png",
    "PAG39-6.png",
  ],
  40: "",
  41: "PAG41-1.png",
  42: ["PAG42-1.png", "PAG42-2.png", "PAG42-3.png", "PAG42-4.png"],
  43: ["PAG43-1.png", "PAG43-2.png"],
  44: "PAG44-1.png",
  45: "PAG45-1.png",
  46: [
    "PAG46-1.png",
    "PAG46-2.png",
    "PAG46-3.png",
    "PAG46-4.png",
    "PAG46-5.png",
  ],
  47: "PAG47-1.png",
  48: ["PAG48-1.png", "PAG48-2.png"],
  49: "",
  50: "PAG50-1.png",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
  58: "",
};
const images_sm_Data = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: "PAG4-1.png",
  5: "PAG5-1.png",
  6: ["PAG6-1.png", "PAG6-2.png"],
  7: "PAG7-1.png",
  8: ["PAG8-1.png", "PAG8-2.png", "PAG8-3.png", "PAG8-4.png", "PAG8-5.png"],
  9: "PAG9-1.png",
  10: "PAG10-1.png",
  11: [
    "PAG11-1.png",
    "PAG11-2.png",
    "PAG11-3.png",
    "PAG11-4.png",
    "PAG11-5.png",
  ],
  12: "PAG12-1.png",
  13: [
    "PAG13-1.png",
    "PAG13-2.png",
    "PAG13-3.png",
    "PAG13-4.png",
    "PAG13-5.png",
  ],
  14: "",
  15: "",
  16: "PAG16-1.png",
  17: [
    "PAG17-1.png",
    "PAG17-2.png",
    "PAG17-3.png",
    "PAG17-4.png",
    "PAG17-5.png",
  ],
  18: "",
  19: "PAG19-1.png",
  20: [
    "PAG20-1.png",
    "PAG20-2.png",
    "PAG20-3.png",
    "PAG20-4.png",
    "PAG20-5.png",
  ],
  21: ["PAG21-1.png", "PAG21-2.png"],
  22: "PAG22-1.png",
  23: ["PAG23-1.png", "PAG23-2.png"],
  24: "PAG24-1.png",
  25: [
    "PAG25-1.png",
    "PAG25-2.png",
    "PAG25-3.png",
    "PAG25-4.png",
    "PAG25-5.png",
  ],
  26: "PAG26-1.png",
  27: [
    "PAG27-1.png",
    "PAG27-2.png",
    "PAG27-3.png",
    "PAG27-4.png",
    "PAG27-5.png",
  ],
  28: "PAG28-1.png",
  29: "PAG29-1.png",
  30: "PAG30-1.png",
  31: [
    "PAG31-1.png",
    "PAG31-2.png",
    "PAG31-3.png",
    "PAG31-4.png",
    "PAG31-5.png",
  ],
  32: "",
  33: "",
  34: "PAG34-1.png",
  35: ["PAG35-1.png", "PAG35-2.png"],
  36: "PAG36-1.png",
  37: ["PAG37-1.png", "PAG37-2.png"],
  38: "",
  39: [
    "PAG39-1.png",
    "PAG39-2.png",
    "PAG39-3.png",
    "PAG39-4.png",
    "PAG39-5.png",
    "PAG39-6.png",
  ],
  40: "",
  41: "PAG41-1.png",
  42: ["PAG42-1.png", "PAG42-2.png", "PAG42-3.png", "PAG42-4.png"],
  43: ["PAG43-1.png", "PAG43-2.png"],
  44: "PAG44-1.png",
  45: "PAG45-1.png",
  46: [
    "PAG46-1.png",
    "PAG46-2.png",
    "PAG46-3.png",
    "PAG46-4.png",
    "PAG46-5.png",
  ],
  47: "PAG47-1.png",
  48: ["PAG48-1.png", "PAG48-2.png"],
  49: "",
  50: "PAG50-1.png",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
  58: "",
};
const images_ms_Data = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: "PAG4-1.png",
  5: "PAG5-1.png",
  6: ["PAG6-1.png", "PAG6-2.png"],
  7: "PAG7-1.png",
  8: ["PAG8-1.png", "PAG8-2.png", "PAG8-3.png", "PAG8-4.png", "PAG8-5.png"],
  9: "PAG9-1.png",
  10: "PAG10-1.png",
  11: [
    "PAG11-1.png",
    "PAG11-2.png",
    "PAG11-3.png",
    "PAG11-4.png",
    "PAG11-5.png",
  ],
  12: "PAG12-1.png",
  13: [
    "PAG13-1.png",
    "PAG13-2.png",
    "PAG13-3.png",
    "PAG13-4.png",
    "PAG13-5.png",
  ],
  14: "",
  15: "",
  16: "PAG16-1.png",
  17: [
    "PAG17-1.png",
    "PAG17-2.png",
    "PAG17-3.png",
    "PAG17-4.png",
    "PAG17-5.png",
  ],
  18: "",
  19: "PAG19-1.png",
  20: [
    "PAG20-1.png",
    "PAG20-2.png",
    "PAG20-3.png",
    "PAG20-4.png",
    "PAG20-5.png",
  ],
  21: ["PAG21-1.png", "PAG21-2.png"],
  22: "PAG22-1.png",
  23: ["PAG23-1.png", "PAG23-2.png"],
  24: "PAG24-1.png",
  25: [
    "PAG25-1.png",
    "PAG25-2.png",
    "PAG25-3.png",
    "PAG25-4.png",
    "PAG25-5.png",
  ],
  26: "PAG26-1.png",
  27: [
    "PAG27-1.png",
    "PAG27-2.png",
    "PAG27-3.png",
    "PAG27-4.png",
    "PAG27-5.png",
  ],
  28: "PAG28-1.png",
  29: "PAG29-1.png",
  30: "PAG30-1.png",
  31: [
    "PAG31-1.png",
    "PAG31-2.png",
    "PAG31-3.png",
    "PAG31-4.png",
    "PAG31-5.png",
  ],
  32: "",
  33: "",
  34: "PAG34-1.png",
  35: ["PAG35-1.png", "PAG35-2.png"],
  36: "PAG36-1.png",
  37: ["PAG37-1.png", "PAG37-2.png"],
  38: "",
  39: [
    "PAG39-1.png",
    "PAG39-2.png",
    "PAG39-3.png",
    "PAG39-4.png",
    "PAG39-5.png",
    "PAG39-6.png",
  ],
  40: "",
  41: "PAG41-1.png",
  42: ["PAG42-1.png", "PAG42-2.png", "PAG42-3.png", "PAG42-4.png"],
  43: ["PAG43-1.png", "PAG43-2.png"],
  44: "PAG44-1.png",
  45: "PAG45-1.png",
  46: [
    "PAG46-1.png",
    "PAG46-2.png",
    "PAG46-3.png",
    "PAG46-4.png",
    "PAG46-5.png",
  ],
  47: "PAG47-1.png",
  48: ["PAG48-1.png", "PAG48-2.png"],
  49: "",
  50: "PAG50-1.png",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
  58: "",
};
const imagesData = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: "PAG4-1.png",
  5: "PAG5-1.png",
  6: ["PAG6-1.png", "PAG6-2.png"],
  7: "PAG7-1.png",
  8: ["PAG8-1.png", "PAG8-2.png", "PAG8-3.png", "PAG8-4.png", "PAG8-5.png"],
  9: "PAG9-1.png",
  10: "PAG10-1.png",
  11: [
    "PAG11-1.png",
    "PAG11-2.png",
    "PAG11-3.png",
    "PAG11-4.png",
    "PAG11-5.png",
  ],
  12: "PAG12-1.png",
  13: [
    "PAG13-1.png",
    "PAG13-2.png",
    "PAG13-3.png",
    "PAG13-4.png",
    "PAG13-5.png",
  ],
  14: "",
  15: "",
  16: "PAG16-1.png",
  17: [
    "PAG17-1.png",
    "PAG17-2.png",
    "PAG17-3.png",
    "PAG17-4.png",
    "PAG17-5.png",
  ],
  18: "",
  19: "PAG19-1.png",
  20: [
    "PAG20-1.png",
    "PAG20-2.png",
    "PAG20-3.png",
    "PAG20-4.png",
    "PAG20-5.png",
  ],
  21: ["PAG21-1.png", "PAG21-2.png"],
  22: "PAG22-1.png",
  23: ["PAG23-1.png", "PAG23-2.png"],
  24: "PAG24-1.png",
  25: [
    "PAG25-1.png",
    "PAG25-2.png",
    "PAG25-3.png",
    "PAG25-4.png",
    "PAG25-5.png",
  ],
  26: "PAG26-1.png",
  27: [
    "PAG27-1.png",
    "PAG27-2.png",
    "PAG27-3.png",
    "PAG27-4.png",
    "PAG27-5.png",
  ],
  28: "PAG28-1.png",
  29: "PAG29-1.png",
  30: "PAG30-1.png",
  31: [
    "PAG31-1.png",
    "PAG31-2.png",
    "PAG31-3.png",
    "PAG31-4.png",
    "PAG31-5.png",
  ],
  32: "",
  33: "",
  34: "PAG34-1.png",
  35: ["PAG35-1.png", "PAG35-2.png"],
  36: "PAG36-1.png",
  37: ["PAG37-1.png", "PAG37-2.png"],
  38: "",
  39: [
    "PAG39-1.png",
    "PAG39-2.png",
    "PAG39-3.png",
    "PAG39-4.png",
    "PAG39-5.png",
    "PAG39-6.png",
  ],
  40: "",
  41: "PAG41-1.png",
  42: ["PAG42-1.png", "PAG42-2.png", "PAG42-3.png", "PAG42-4.png"],
  43: ["PAG43-1.png", "PAG43-2.png"],
  44: "PAG44-1.png",
  45: "PAG45-1.png",
  46: [
    "PAG46-1.png",
    "PAG46-2.png",
    "PAG46-3.png",
    "PAG46-4.png",
    "PAG46-5.png",
  ],
  47: "PAG47-1.png",
  48: ["PAG48-1.png", "PAG48-2.png"],
  49: "",
  50: "PAG50-1.png",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
  58: "",
};

const buttonsNameData = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: "",
  5: [
    "Actividad de inicio 1",
    "Aspectos fundamentales de la Justicia Restaurativa en la unidad edu-cativa",
    "Tipos de la violencia en el sistema educativo",
    "Consecuencias emocionales por agresión",
    "Actividad sugerida 1",
  ],
  6: "",
  7: "",
  8: "",
  9: "",
  10: "",
  11: "",
  12: "",
  13: "",
  14: "",
  15: "",
  16: "",
  17: "",
  18: "",
  19: "",
  20: "",
  21: "",
  22: [
    "Actividad de inicio 2",
    "Las bases de una comunidad educativa restaurativa",
    "Maestras y maestros como facilitadores de las prácticas restaurativas",
    "Consejo Educativo en la pre-vención de conflictos. ",
    "Actividad de sugerida 2",
  ],
  23: "",
  24: "",
  25: "",
  26: "",
  27: "",
  28: "",
  29: "",
  30: "",
  31: "",
  32: "",
  33: "",
  34: "",
  35: "",
  36: [
    "Actividad de inicio 3",
    "Concepto y características de una zona restaurativa. ",
    "El rol de los integrantes de la comunidad educativa en una zona restaurativa. ",
    "Actividades con enfoque restaurativo. ",
    "Actividad sugerida 3",
  ],
  37: "",
  38: "",
  39: "",
  40: "",
  41: "",
  42: "",
  43: "",
  44: "",
  45: "",
  46: "",
  47: "",
  48: "",
  49: ["Información", "Interpretación", "Conclusiones", "Estrategias"],
  50: "",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
  58: "",
};

const buttonsPageNumberData = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: "",
  5: [6, 8, 13, 17, 21],
  6: "",
  7: "",
  8: "",
  9: "",
  10: "",
  11: "",
  12: "",
  13: "",
  14: "",
  15: "",
  16: "",
  17: "",
  18: "",
  19: "",
  20: "",
  21: "",
  22: [23, 25, 26, 30, 35],
  23: "",
  24: "",
  25: "",
  26: "",
  27: "",
  27: "",
  28: "",
  29: "",
  30: "",
  31: "",
  32: "",
  33: "",
  34: "",
  35: "",
  36: [37, 39, 40, 41, 48],
  37: "",
  38: "",
  39: "",
  40: "",
  41: "",
  42: "",
  43: "",
  44: "",
  45: "",
  46: "",
  47: "",
  48: "",
  49: "",
  50: "",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
  58: "",
};
const linksData = {
  0: "",
  1: "",
  2: "",
  3: "",
  4: "",
  5: "",
  6: "https://docs.google.com/document/d/1-jTLU0A5cKWr_OA_k-Ln4wNtTH8it6kN/edit?usp=sharing&ouid=118068284416475194361&rtpof=true&sd=true",
  7: "",
  8: "",
  9: "",
  10: "",
  11: "",
  12: "",
  13: "",
  14: "",
  15: "",
  16: "",
  17: "",
  18: "",
  19: "",
  20: "",
  21: "https://docs.google.com/document/d/1tJRUBPyurcpBiLI52OfeZilL4A_yzv4g/edit?usp=sharing&ouid=118068284416475194361&rtpof=true&sd=true",
  22: "",
  23: "https://docs.google.com/document/d/1K48eFeWpkiVs4OVP2B4wwxse_2o9B937/edit?usp=sharing&ouid=118068284416475194361&rtpof=true&sd=true",
  24: "",
  25: "",
  26: "",
  27: "",
  27: "",
  28: "",
  29: "",
  30: "",
  31: "",
  32: "",
  33: "",
  34: "",
  35: "https://docs.google.com/document/d/15GuF7YYEdho9nRh8bOMQuqIgVbpqfB35/edit?usp=sharing&ouid=118068284416475194361&rtpof=true&sd=true",
  36: "",
  37: "https://docs.google.com/document/d/1PwuDfAxx-fkcwcvRMhU_grvdlj6fAy7E/edit?usp=sharing&ouid=118068284416475194361&rtpof=true&sd=true",
  38: "",
  39: "",
  40: "",
  41: "",
  42: "",
  43: "",
  44: "",
  45: "",
  46: "",
  47: "",
  48: "https://docs.google.com/document/d/1uZ9BUDg9KfxfL4P1B9F2WEGNhVxszv2H/edit?usp=sharing&ouid=118068284416475194361&rtpof=true&sd=true",
  49: "",
  50: "",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
};
