const popUpData = {
  0: " ",
  1: "",
  2: "",
  3: "",
  4: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG4POP-1_SM.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG4POP-2_SM.png",
      buttonName: "Abrir",
    },
  ],
  5: "",
  6: "",
  7: "",
  8: "",
  9: "",
  10: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG10POP-1_SM.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG10POP-2_SM.png",
      buttonName: "Abrir",
    },
  ],
  11: "",
  12: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG12POP-1_SM.png",
      buttonName: "Abrir",
    },
    //{
    //  title: "Titulo del modal1111DDD",
    //  typeofContent: "text",
    //   contentModal:
    //    "tezto a remplazar",
    //   buttonName: "+",
    //  },
  ],
  13: "",
  14: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG14POP-1_SM.png",
      buttonName: "Manifestación del bullying",
    },
  ],
  15: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG15POP-1_SM.png",
      buttonName: "Internet y Bullying",
    },
  ],
  16: "",
  17: "",
  18: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG18POP-1_SM.png",
      buttonName: "Fortalecer sentido de comunidad",
    },
  ],
  19: "",
  20: "",
  21: "",
  22: "",
  23: "",
  24: "",
  25: "",
  26: [
    //{
    // title: "Titulo del modal000DDD",
    //typeofContent: "image",
    //contentModal: "layOutD.jpg",
    //buttonName: "+",
    //},
    {
      title: " ",
      typeofContent: "text",
      contentModal:
        "Las prácticas restaurativas en el ámbito educativo se basan en el desarrollo de la comunidad a partir del fortalecimiento de los vínculos. Cuando se dan conflictos en la vida del centro, lo que se busca es la reparación de los daño o falta u ofensas causados asumiendo responsabilidades. (Gonzales, 2022)",
      buttonName: "Abrir",
    },
  ],
  27: "",
  28: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG28POP-1_SM.png",
      buttonName: "Abrir",
    },
    //{
    //  title: "Titulo del modal1111DDD",
    //  typeofContent: "text",
    //   contentModal:
    //    "tezto a remplazar",
    //   buttonName: "+",
    //  },
  ],
  29: "",
  30: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG30POP-1_SM.png",
      buttonName: "Abrir",
    },
    //{
    //  title: "Titulo del modal1111DDD",
    //  typeofContent: "text",
    //   contentModal:
    //    "tezto a remplazar",
    //   buttonName: "+",
    //  },
  ],
  31: "",
  32: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG32POP-1_SM.png",
      buttonName: "Estudiante consciente",
    },
  ],
  33: [
    {
      title: "",
      typeofContent: "image",
      contentModal: "PAG33POP-1_SM.png",
      buttonName: "Prevención de conflictos estudiantiles",
    },
  ],
  34: [
    {
      title: "Para la prevención de conflictos y violencia",
      typeofContent: "image",
      contentModal: "PAG34POP-1_SM.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG34POP-2_SM.png",
      buttonName: "Abrir",
    },
  ],
  35: "",
  36: "",
  37: "",
  38: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG38POP-1_SM.png",
      buttonName: "Zona restaurativa",
    },
  ],
  39: "",
  40: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-1_SM.png",

      buttonName: "El niño, niña, adolescente o persona adulta ofensora",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-2_SM.png",

      buttonName: "El niño, niña, adolescente o persona adulta víctima",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-3_SM.png",

      buttonName: "La comunidad educativa",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-4_SM.png",
      buttonName: "Facilitadores de la práctica",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG40POP-5_SM.png",
      buttonName: "Las autoridades de gestión y dirección",
    },
  ],
  41: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG41POP-1_SM.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG41POP-2_SM.png",
      buttonName: "Abrir",
    },
  ],
  42: "",
  43: "",
  44: "",
  45: "",
  46: "",
  47: [
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG47POP-1_SM.png",
      buttonName: "Abrir",
    },
    {
      title: " ",
      typeofContent: "image",
      contentModal: "PAG47POP-2_SM.png",
      buttonName: "Abrir",
    },
  ],
  48: "",
  49: "",
  50: "",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
  58: "",
};
const imagesData = {
  0: " ",
  1: "",
  2: "",
  3: "",
  4: "PAG4-1_SM.png",
  5: "PAG5-1_SM.png",
  6: ["PAG6-1_SM.png", "PAG6-2_SM.png"],
  7: "PAG7-1_SM.png",
  8: [
    "PAG8-1_SM.png",
    "PAG8-2_SM.png",
    "PAG8-3_SM.png",
    "PAG8-4_SM.png",
    "PAG8-5_SM.png",
  ],
  9: "PAG9-1_SM.png",
  10: "PAG10-1_SM.png",
  11: [
    "PAG11-1_SM.png",
    "PAG11-2_SM.png",
    "PAG11-3_SM.png",
    "PAG11-4_SM.png",
    "PAG11-5_SM.png",
  ],
  12: "PAG12-1_SM.png",
  13: [
    "PAG13-1_SM.png",
    "PAG13-2_SM.png",
    "PAG13-3_SM.png",
    "PAG13-4_SM.png",
    "PAG13-5_SM.png",
  ],
  14: "",
  15: "",
  16: "PAG16-1_SM.png",
  17: [
    "PAG17-1_SM.png",
    "PAG17-2_SM.png",
    "PAG17-3_SM.png",
    "PAG17-4_SM.png",
    "PAG17-5_SM.png",
  ],
  18: "",
  19: "PAG19-1_SM.png",
  20: [
    "PAG20-1_SM.png",
    "PAG20-2_SM.png",
    "PAG20-3_SM.png",
    "PAG20-4_SM.png",
    "PAG20-5_SM.png",
  ],
  21: ["PAG21-1_SM.png", "PAG21-2_SM.png"],
  22: "PAG22-1_SM.png",
  23: ["PAG23-1_SM.png", "PAG23-2_SM.png"],
  24: "PAG24-1_SM.png",
  25: [
    "PAG25-1_SM.png",
    "PAG25-2_SM.png",
    "PAG25-3_SM.png",
    "PAG25-4_SM.png",
    "PAG25-5_SM.png",
  ],
  26: "PAG26-1_SM.png",
  27: [
    "PAG27-1_SM.png",
    "PAG27-2_SM.png",
    "PAG27-3_SM.png",
    "PAG27-4_SM.png",
    "PAG27-5_SM.png",
  ],
  28: "PAG28-1_SM.png",
  29: "PAG29-1_SM.png",
  30: "PAG30-1_SM.png",
  31: [
    "PAG31-1_SM.png",
    "PAG31-2_SM.png",
    "PAG31-3_SM.png",
    "PAG31-4_SM.png",
    "PAG31-5_SM.png",
  ],
  32: "",
  33: "",
  34: "PAG34-1_SM.png",
  35: ["PAG35-1_SM.png", "PAG35-2_SM.png"],
  36: "PAG36-1_SM.png",
  37: ["PAG37-1_SM.png", "PAG37-2_SM.png"],
  38: "",
  39: [
    "PAG39-1_SM.png",
    "PAG39-2_SM.png",
    "PAG39-3_SM.png",
    "PAG39-4_SM.png",
    "PAG39-5_SM.png",
    "PAG39-6_SM.png",
  ],
  40: "",
  41: "PAG41-1_SM.png",
  42: ["PAG42-1_SM.png", "PAG42-2_SM.png", "PAG42-3_SM.png", "PAG42-4_SM.png"],
  43: ["PAG43-1_SM.png", "PAG43-2_SM.png"],
  44: "PAG44-1_SM.png",
  45: "PAG45-1_SM.png",
  46: [
    "PAG46-1_SM.png",
    "PAG46-2_SM.png",
    "PAG46-3_SM.png",
    "PAG46-4_SM.png",
    "PAG46-5_SM.png",
  ],
  47: "PAG47-1_SM.png",
  48: ["PAG48-1_SM.png", "PAG48-2_SM.png"],
  49: "",
  50: "PAG50-1_SM.png",
  51: "",
  52: "",
  53: "",
  54: "",
  55: "",
  56: "",
  57: "",
  58: "",
};
